### ISSUE TITLE
Vizualizare contract PDF

### ISSUE THREAD

**Issue by GabrielaFlorescu** [posfgit/standard#103]
Va rog sa confirmati faptul ca un user care isi creeaza cont in POSF nu va avea acces la PDF-ul contractului actual de furnizare pentru un CLC/POD pe care si l-a asociat.

**Comment by bogdannedelcu** [comment]
Un user va avea acces la contractele initiate doar de contul respectiv in platforma POSF. Contracte efectuate la ghiseu nu vor fi asociate userilor din POSF, contractele vor ramane asociate notiunii de client.

Mentionam ca este posibil ca in cursul anului viitor, prin integrarea cu platforma PSCID, sa putem identifica clientul care detine un anumit user in POSF, motiv pentru care vom analiza posibilitatea sa afisam toate contractele unui utilizator identificat (ale CNP-ului respectiv).
