### ISSUE TITLE
Upload documente necesare incheierii contractului

### ISSUE THREAD

**Issue by GabrielaFlorescu** [posfgit/standard#104]
Conform cu cele discutate mai demult (issue #24) si in sedinta de astazi, va rugam sa ne reconfirmati faptul ca documentele pe care furnizorul le solicita clientului vor fi incarcate cu butoane diferite (de ex. daca prin oferta solicitam 6 documente contractuale, clientul va trebui sa apese pe 6 butoane si nu va putea trece mai departe daca nu le-a incarcat pe toate)

**Comment by bogdannedelcu** [comment]
veti primi acces la aplicatia Web pentru care va rugam sa faceti observatii si sa ne transmiteti propunerile de imbunatatire.
