### ISSUE TITLE
Open Point - Mediu de test POSF

### ISSUE THREAD

**Issue by dansilviuiancu** [posfgit/standard#12]
Buna ziua,
Va multumim foarte mult pentru informatiile transmise. O singura nelamurire as avea si este legata de mediu de test:
https://github.com/posfgit/standard/tree/main/samples/python.

Acest mediu trebuie instalat de noi si o sa il folosim in etapa de dezvoltare , urmand ca in etapa de integrare sa ne puneti dvs. la dispozitie un mediu de test sau aveti deja un mediu de test pe care sa ni-l puneti la dispozitie inclusiv in etapa de dezvoltare?

Multumesc .

**Comment by bogdannedelcu** [comment]
Ati inteles corect, il puteti folosi ca si demo initial. Revenim saptamanile care urmeaza cu un mediu de test hostat la ANRE cu care veti putea interactiona de la distanta si testa diverse functionalitati.

**Comment by dansilviuiancu** [comment]
Va multumesc frumos!
