### ISSUE TITLE
Propunere eliminare cod SIRUTA ca parametru in interogarea API-ului pentru PLACE-uri

### ISSUE THREAD

**Issue by ItSupportRenovatioTrading** [posfgit/standard#122]
Nomenclatorul de orase si judete INNS ofera informatii cu o granulatie mare , iar asta inseamna ca foarte multe denumiri pot fi duplicate intr-ucat ele pot face referire (de exemplu) atat la oras cat si la o zona administrativa sau comuna. 

Ca sa intelegeti, iau ca exemplu o cautare dupa numele "Brosteni" si observ ca aceasta localitate din jud. DB o regasesc in mai multe inregistrari cu coduri SIRUTA diferite cf imaginii: 

![image](https://user-images.githubusercontent.com/108864388/184308070-f2847cf4-5791-46ab-9a9b-3ea439cbf2d7.png)

de unde se poate identifica faptul ca in DB aceasta localitate este inregistrata cu 3 coduri SIRUTA.

Cautand in baza de date a [siruta.nxm.ro](url) dupa acelasi nume de localitate, observ conform imaginii un set de rezultate la fel de stufos:

![image](https://user-images.githubusercontent.com/108864388/184309088-79ed2700-d8a7-4e9f-8f71-6bd279401960.png)

iar mai detaliat, o cautare dupa cod SIRUTA `68547` in [siruta.nxm.ro](url) , pot observa ca e vorba de un sat din comuna Produlesti, jud. Dambovita

![image](https://user-images.githubusercontent.com/108864388/184309799-291ce61f-3eed-41da-bc71-0e37ba55ea9c.png) 

in timp ce `66358` este un sat din comuna Brezdead, jud. Dambovita

![image](https://user-images.githubusercontent.com/108864388/184310706-d30f3b8c-595b-473b-9e84-618608275176.png) 

sau `69358` care este un sat din com. Visina, jud. Dambovita (nu mai pun screen).

In acest moment , nu cunosc granulatia fiecarui sistem in parte; unele, probabil, au o granulatie a detaliilor mai redusa, de exemplu `Nume Localitate` si  `Judet` , fara alte detalii sau pur si simplu nu tin o evidenta atat de detaliata in adrese si, in situatia asta, este imposibil sa faci selectia corecta a codului SIRUTA atunci cand "ceri" un Place.

Din discutiile cu Bogdan Nedelcu, am inteles ca s-a ales varianta de parametrizare a interogarii API-ului de Place-uri in baza codului SIRUTA pentru a se evita rezultatele cu mai multe Place-uri pentru un POD/CLC. 

Avand in vedere ca POD/CLC sunt UNICE, consider ca o interogare pe API-ul de Place-uri ar fi suficient sa contina parametrii `COD` si `TYPE` (CLC/POD)  

Unicitatea ar permite, de asemenea, stabilirea unui PRIMARY KEY la nivel de `POD` / `CLC` , ceea ce ar imbunatati performanta de cautare. 

S-ar putea pastra, pentru a restrictiona o eventuala interogare neautorizata, parametrul `COD JUDET`. Considerand ca trebuie sa stii macar judetul in care se afla POD-ul.

Avand cele explicate mai sus, propun eliminarea codului SIRUTA din parametrii de interogare a API-ului pentru Place-uri si m-ar ajuta sa aflu si parerea dvs tuturor. 

Multumesc anticipat!

**Comment by EDistributie** [comment]
Eu nu sunt de acord cu dumneavoastra. Este nevoie de codul SIRUTA tocmai pentru a face diferenta intre numele satelor multiple din fiecare judet. Exemplul dumneavoastra, in Judetul Dambovita exista 3 sate care au aceeasi denumire: Brosteni. Aceste sate fac parte din comune diferite:
1.  Comuna Bezdead --> Sat Brosteni 66358	
![image](https://user-images.githubusercontent.com/103568621/184325369-1d392d7a-f85a-45bc-8fae-139bfe587dbc.png)
2. Comuna Produlesti --> Sat Brosteni 68547	
![image](https://user-images.githubusercontent.com/103568621/184325572-fc36dedd-b190-44b3-a796-0846d9a50d0d.png)
3. Comuna Visina --> Sat Brosteni 69358	
![image](https://user-images.githubusercontent.com/103568621/184325704-dfd6172c-4fcb-40d2-a907-204c905fa3fa.png)

Prin urmare, consider necesar folosirea codului SIRUTA asa cum a fost prevazut initial.

**Comment by ItSupportRenovatioTrading** [comment]
Deci inteleg, din ceea ce imi spuneti, ca POD/CLC -urile  din sistemul EDistributie, NU sunt unice, si ar putea exista situatia sa regasesc acelasi POD in doua comune. Am inteles bine? Si daca este asa, inseamna ca distributiile recicleaza codurile POD  la fel ca cum operatorii de telefonie mobila recicleaza numerele de telefon.

Codul SIRUTA este foarte util in sistemele proprii si in POSF, total de acord cu aceasta abordare. Noi am recomandat (si asta doar in cazul in care POD/CLC sunt unice si nereciclabile) eliminarea PARAMETRULUI DE CAUTARE SIRUTA din API-ul de Place-uri fiind suficienta identificarea unui Place dupa cod POD/CLC.

**Comment by bogdannedelcu** [comment]
Pe mediul de test si cel de staging regasiti un nou API de accesare a locurilor de consum pornind doar de la codul CLC/POD. Noua cale de acces este de forma /broker/place/{type}/{code} ex: https://posf-beta.anre.ro/broker/place/CLC/612-229-1785 raspunsul fiind o lista de locuri de consum care au acel cod indiferent de judetul sau orasul unde au fost incarcate de OR.

**Comment by ItSupportRenovatioTrading** [comment]
Multumesc! Voi inchide acest `issue`.
