### ISSUE TITLE
ContractNetworkChangedInfo raspuns OR

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#128]
Fluxul ContractNetworkChangedInfo se poate utiliza pentru a cere mai multe detalii din partea OR ca raspuns al mesajului ContractSignedBySupplier? De exemplu, in cazul in care furnizorul sau clientul final nu trimite indexul conform instructiunilor OR din campul counterIndexDesc, OR poate mentiona in campul "Info" restransmiterea indexului ? Multumesc!

**Comment by bogdannedelcu** [comment]
Nu este prevazut mesaj pentru a cere mai multe informatii de la OR spre FN prin POSF

**Comment by EDistributie** [comment]
Ok, multumesc de informare. Poate pe viitor se poate lua in calcul aceasta propunere
