### ISSUE TITLE
DEER_IT_soliicatre clarificari

### ISSUE THREAD

**Issue by DEERITAF** [posfgit/standard#15]
Referitor la tranzactiile de schimb de date:
a)	avem nevoie de o imagine clara a mesajelor de schimb de date intre POSF si Distribuitor:
- in varianta finala de functionare intre PODF si Distribuitor raman cele 4 mesaje din schema ? 
- este necesara o imagine clara a fiecarui mesaj de schimb de date cu campuri si tip de data pentru a putea analiza datele ce trebuie comunicate sau inregistrate in SAP.
- e nevoie  sa stim clar ce campuri sunt optionale sau obligatorii (De ex. la crearea unui POD nu avem si info despre contoare pt ca contoarele se monteaza la contractare nu la crearea POD deci info despre contor nu poate fi obligatorie)
b)	Orice proces initiat de una din parti ar trebui sa primesca o confirmare de primire din partea celeilate , nu am vazut asa ceva prevazut in schema de interfatare
c)	Tranzactiile  sunt si in romana  si in enegleza. De exemplu “Convention Signed By Operator “ poate insemna ca se transmite conventia de consum sau ca s-a inregistrat contractual. Consideram necesara traducerea in romana a tuturor mesajelor de schimb de date pentru a nu exista confuzii in interpretarea lor.

Multumim!

**Comment by bogdannedelcu** [comment]
Buna ziua,

Regasiti pe prima pagina a standardului tabele noi cu toate mesajele identificate pana acum, emitentul si destinatarii catre care va fi redirectionat mesajul. Urmarind aceste detalii, in functie de rolul sistemului dvs. puteti vedea ce mesaje puteti trimite si ce mesaje puteti receptiona.

Referitor la campurile obligatorii este util feedback-ul dvs. pentru toate campurile din schema, va rog sa ne transmiteti ce anume detineti/puteti completa si ce nu, asa incat sa putem actualiza specificatiile.

Am retinut sugestia, vom modifica specificatiile pentru a raspunde din interfata /broker/postMessage cu un mesaj de confirmare, referind mesajul transmis.

In denumirea mesajelor am incarcat sa implementam conventia: Subiect-Actiune-Autor: Conventia Semnata de Operator

Multumim
