### ISSUE TITLE
ENGIE Romania - solicitare lamuriri suplimentare POSF

### ISSUE THREAD

**Issue by iuliavasilescu** [posfgit/standard#16]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/IULIAV~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/IULIAV~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/IULIAV~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal>Buna ziua,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>In acest moment avem la dispozitie o serie de informatii
tehnice, pe baza carora ar trebui sa construim fluxuri de business cu drepturi
si obligatii din partea fiecarui actor implicat in procesele de contractare /
schimbare furnizor (POSF, OSD, CF, FA, FN). <o:p></o:p></p>

<p class=MsoNormal>Ca exemplu, in platforma posfgit, spatiul virtual pus la
dispozitie pentru clarificari, avem o serie de scheme ce includ mesaje tehnice
care impun o obligativitate de transmitere a unor informatii, care nu sunt la
dispozitia furnizorului (ele regasindu-se in POSF,<o:p></o:p></p>

<p class=MsoNormal>incarcate de catre OSD sau alte parti implicate) sau nu sunt
colectate la momentul contractarii si care poate ar trebui definite ca
optionale. <o:p></o:p></p>

<p class=MsoNormal>Va rugam sa prezentati fluxurile business si schemele de
proces ce vor fi configurate in POSF in relatie cu furnizorii si CF (in cazul
contractarii direct prin POSF).<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Am aprecia foarte mult disponibilitatea unei intalniri cu
dumnevoastra, precum si constituirea unui grup de lucru pentru creionarea
fluxurilor de business, cu participarea tuturor operatorilor implicati.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Urmatoarele intrebari sunt formulate, ca urmare a lipsei de
informatii pe care o avem in privinta solutiei POSF, raportat la prevederile
Ordinului 3/2022:<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

1 | Art.15 pct.1 i) si pct.2 h) | Se prevede existenta in POSF a starii locurilor de consum,   respectiv conectat/deconectat. In cazul modificarii acestei stari,   actualizarea de catre OR va avea loc in timp real, incat furnizorii sa poata   prelua aceasta informatie? Se va permite contractarea pentru un loc de consum   deconectat? Va exista un API care sa permita interogarea informatiei despre   starea locului de consum? Va fi posibil ca un furnizor sa interogheze in timp   real, pe baza POD/CLC, in timpul procesului de contractare, date despre locul   de consum la care este conectat CF (de ex. date istorice de consum in vederea   completarii conventiei de consum)?
-- | -- | --
2 | Art 15 | Regulamentul nu prevede captarea codului CAEN de la CF   noncasnici – va fi adaugat totusi ca element necesar in POSF? Codul CAEN   serveste cel mai bine la segmentarea CF noncasnici.
3 | Art.16 (2) | Care este modalitatea in care POSF va returna catre   furnizor si OR informatia referitoare la faptul ca nu corespund adresele   locului de consum inregistrate de furnizor/OR cu nomenclatorul de adrese din   POSF? Cum se procedeaza in cazul in care adresa locului de consum din   nomenclatorul POSF nu corespunde cu adresa locului de consum comunicata de   catre client la incheierea contractului de furnizare? Adresele se   actualizeaza in mod continuu. In procesul de schimbare furnizor ar trebui sa   fie luata in considerare ultima adresa incarcata, furnizata de catre client.
4 | art 34 pct 1 lit b) | In cazul in care platforma POSF va fi indisponibila dpdv   tehnic, termenul prevazut la art 34 pct 1 lit b) se va decala cu numarul de   zile aferent perioadei de nefunctionare a platformei?
5 | Art 34 pct 4 lit e) | Va rugam sa definiti fluxul de notificare incetare   contract - o astfel de notificare este transmisa si catre FA? Mentinam ca   aceasta este necesara FA in vederea actualizarii datei de final a   contractului de furnizare in sistemul informatic.
6 | Art.34 pct.a) (ii) | In conformitate cu Regulamentul de furnizare a energiei   electrice la clientii finali Ordinul ANRE nr. 235/2019  si  privind   furnizarea gazelor naturale la clientii finali Ordinul ANRE nr. 29/2016 ,   documentele necesare contractarii sunt:   1. cererea de contractare;    2. copia actului de identitate/ certificatul de inregistrare ONRC;   3. declaratia pe proprie raspundere cu privire la detinerea spatiului locativ   respectiv a lipsei litigiilor locative.   Rugam autoritatea sa detalieze De detaliat fluxul de preluare prin POSF    a acestor date/ informatii/ documente necesare din partea clientului conform   regulamentelor anterior citate.   In cazul in care clientul alege contractare prin POSF, documentele de la   punctele 1 si 3 vor  fi completate si semnate de client direct in   platforma fara downloaduri / uploaduri intermediare din partea acestuia? Sau   declaratiile si acordurile vor fi preluate ca bife si transmise FA? In cazul   in care furnizorul are nevoie de documente suplimentare/ lamuriri din partea   clientului, are posibilitatea sa ceara completari prin intermediul   POSF?
7 | Art.34 pct.a) (iii) | In cazul incheierii contractului de furnizare de catre CF   direct in POSF, termenul pentru verificarea, validarea si semnarea contractului   de furnizare de catre furnizor este de 24 ore de la data primirii   documentelor de la CF. Ar trebui aliniat cu cel care decurge din Ord.83/2021   art.7 pct (1) si (2) termenul pentru transmiterea contractului semnat este de   5 zile lucratoare de la data inregistrarii documentatiei complete.
8 | Art.34 | Regulamentul prevede semnarea unor contracte de   distributie și rețea în POSF. Va rugam de prezentati fluxul de lucru in   cadrul platformei incluzand detalii dspre mecanismul de  semnare a unui   contract de distributie / anexa la contract de distributie in POSF.   Sunt transmise notificari de expirare termen de semnare a documentelor   mentionate la art 34 alin 4  care sa contina si detalierea urmarilor   nerespectarii acestora (ex - reluare proces contractare in cazul in care   aceasta este o urmare a nesemnarii la timp)?   Care este politica de arhivare si durata de pastrare a acestor contracte de   distributie / acte aditionale la contractele de distributie in cadrul POSF?
9 | Art.39 | Cum se va proceda in cazul locurilor de consum al caror   contract este reziliat la momentul punerii in functiune si   operationalizarii POSF iar CF acceseaza POSF in vederea incheierii unui   contract de furnizare?    Va exista un API care sa permita actualizarea starii unei instalatii in   cadrul POSF?   Spre exemplu in cazul cazul clientilor de gaze naturale reziliati cu contorul   de masurare ridicat de mai mult de 6 luni sau care au realizat ultima revizie   cu mai mult de 10 ani in urma datei solicitarii, conform Regulamentul privind   accesul la sistemele de distribuție a gazelor naturale aprobat prin Ordinul   Președintelui ANRE nr. 97/2018 acestia sunt informati si obligati sa   realizeze revizia tehnică a instalației de utilizare a gazelor naturale. In   functie de ce va recunoaste POSF aceste cazuri? Care sunt optiunile pe care   clientul, furnizorul si OR le au la dispozitie pentru continuarea fluxului?   In cazul in care fluxul este stopat, este transmisa notificare prin care ii   va fi explicata clientului cauza si metodele de reluare a fluxului?
10 | Art.40 | In cazul clientilor in regim FUI, trebuie realizata   preluarea in masa de noul furnizor. Va rugam sa precizati daca in platforma   POSF va exista un proces care sa asigure preluarea in masa a clientilor FUI   si sa prezentati detalii privind fluxul de lucru.
11 | Art.40 (2) corelat cu Art.43 (1) d) | CF preluat in regim de FUI va primi notificare pentru   descarcarea contractului? Ordin 173/2020 Art.26 a) desfasurarea activitatii   de furnizare a gazelor naturale in regim de UI pentru clientii preluati   automat se face fara a fi necesara existenta unui contract Incheiat cu FUI   pentru clientii finali cu un consum annual mai mic sau egal cu 28.000MWh
12 | Art 43 alin 1 lit b | Vor fi incluse in POSF lamuriri legate de cele doua   optiuni pe care clientul le are in privinta serviciilor de distributie   (incheierea contractului prin furnizor sau direct cu OR), diferenta dintre   ele fiind majora si obligand clientul la semnarile succesive de documente   prezentate in art 43 alin 1 lit b).
13 | Cap VII | Renuntarea la schimbarea furnizorului se aplica   contractelor incheiate la distanta. Cum se va face diferenta intre cele   incheiate la distanta si cele incheiate de client in centrele de relatii cu   clientii, incarcate ulterior de furnizor in POSF astfel incat atunci cand   clientul ce se inscrie in cel de-al doilea caz sa nu fie lasat sa ceara   renuntarea prin POSF? Modalitatea incheierii contractului nu este mentionata   in art 15 unde se enumera categoriile de date din POSF.
14 |   | In cazul de schimbare de furnizor pe sensul intrarii in portofoliul   FN, platforma va atentiona FN/client de necesitatea semnarii unui contract de   prosumator in cazul in care el face parte din aceasta categorie de clienti?   (conform Ord 15 / 2022 - Metodologia de stabilire a regulilor de   comercializare a energiei electrice produse în centrale electrice din surse   regenerabile cu putere electrică instalată de cel mult 400 kW pe loc de   consum aparţinând prosumatorilor, contractul de prosumator cu FA ia sfarsit   de drept in momentul plecarii clientului din vechea furnizare)
15 |   | Ce se intampla daca pentru un punct de consum se initiaza   in acelasi timp o schimbare de furnizor si în POSF, si direct la furnizor? Va   rugam sa detaliati aceste reguli de business.
16 |   | Va rugam sa definiti fluxul ce se aplica in cazul   desemnarii OR DUI -  cum vor fi reflectate modificarile in POSF avand in   vedere modificarea codificarilor tehnice ale locurilor de consum?
18 |   | Rugam autoritatea sa clarifice obligatia furnizorilor de   energie electrica/gaze naturale prevazuta la art. 27 lit. b), respectiv sa   asigure, sa desemneze si sa inregistreze reprezentanti, pe categorii de   activitati, in numar suficient, calificati pentru realizarea atributiilor   prevazute de prezentul regulament si sa stabileasca drepturile si   obligatiile individuale, aferente categoriilor respective.

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Va multumim pentru disponibilitate!<o:p></o:p></p>

</body>

</html>

**Comment by bogdannedelcu** [comment]
Ref 1: 
a)	Da.
b)	Da.
c)	Da. Este obligatorie. Reconectarea se face insa dupa înlăturarea cauzei deconectarii.
d)	Da la adresa /place/{code} conform documentatiei
e)	Nu se stocheaza in POSF date istorice despre consum. Se stocheaza doar date minimale despre istoricul contractelor de furnizare (numarul contractului/data/partile/durata).

**Comment by bogdannedelcu** [comment]
Ref 2: Nu, deoarece nu servesc procesului de contractare/schimbare a furnizorului. Codul/codurile CAEN pot fi solicitate de furnizor de la CF prin documentele contractuale.

**Comment by bogdannedelcu** [comment]
Ref 3:

a)	Aplicatia Web va arata datele despre locul de consum asa cum le are inregistrate din ultimul mesaj primit de la Operator care actualizeaza acel loc de consum. Furnizorul poate interoga locul de consum pentru a afisa datele actualizate in sistemul informatic propriu.
b)	Furnizorul care contracteaza actualizeaza informatia, cu utilizarea nomenclatorului de adrese pus la dispozitie de POSF (RENNS). Clientul/Furnizorul pot completa adresa in campul de pe contract "executionAddress" daca aceasta difera de cea din locul de consum.

**Comment by bogdannedelcu** [comment]
Ref 4: Aceasta situatie este reglementata de art. 50.

**Comment by bogdannedelcu** [comment]
Ref 5: Da, este definit un astfel de flux, cu notificari trimise partilor implicate, inclusiv FA (ContractCancelledBySupplier/Client si ContractNetworkCancelledByOperator)

**Comment by bogdannedelcu** [comment]
Ref 6: CF incarca documentele necesare contractarii, indicate in oferta furnizorului si semneaza pe cele precompletate de POSF.

Da pentru semnare document 3. Cererea nu este necesara in POSF. In cazul schimbarii furnizorului FA va fi doar notificat. De confirmat Metaminds.

Da, pentru posibilitatea de a cere completari prin intermediul POSF, daca CF a ales sa utilizeze POSF pentru contractare/schimbare.

**Comment by bogdannedelcu** [comment]
Ref 7: Termenul (maximal) de 5 zile prevazut de Ordinul 83/2021 vizeaza situatia incheierii contractelor in afara POSF.

**Comment by bogdannedelcu** [comment]
Ref 8: Sunt aplicabile prevederile art. 43 alin. (3).

Contractele nu se arhiveaza in POSF ci doar informatii minimale (numar, data, data incetare, parti). Durata de prastrare in POSF la dispozitia partilor este prevazuta la art. 45.

**Comment by bogdannedelcu** [comment]
Ref 9: Locurile respective de consum nu vor avea asociat niciun contract, CF fiind in masura sa aleaga din comparator o oferta si sa initieze procesul de incheiere a unui contract. In aplicatia WebPOSF CF va putea sa vada istoricul contractelor incarcate in sistem pe acel loc de consum, chiar daca sunt reziliate.
Va exista api pentru interogarea locurilor de consum pe baza codului acestora prin interfata /place/{code}
La ce stare va referiti? Daca va referiti la starea conectat/deconectat, inregistrarea informatiei in POSF este in sarcina OR. Datele despre revizia contorului sau a instalatiei de utilizare nu fac obiectul POSF. Aceste informatii se vehiculeaza direct prin relatia OR-Furnizor.
Fluxul de contractare/schimbare furnizor nu este permis sa fie stopat datorita starii tehnice a instalatiei de utilizare.
Din punct de vedere tehnic exista mesaje de tipul ContractMoreInfo prin care se pot schimba mesaje cu privire la particularitatile contractului de furnizare.

**Comment by bogdannedelcu** [comment]
Ref 10: Se vor emite mesaje individuale de tip ContractTransferredToFUIByANRE/Operator spre coada de mesaje a FUI in mod automat. FUI le va citi folosind API.

**Comment by bogdannedelcu** [comment]
Ref 11: Nu. Doar notificare pentru incheierea contractului in afara POSF

**Comment by bogdannedelcu** [comment]
Ref 12: Renuntarea recomandam sa se faca in acelasi fel ca si incheierea contractului.

**Comment by bogdannedelcu** [comment]
Ref 14: Contractul de achizitie a energiei in surplus de la prosumator nu face obiectul POSF. Calitatea de prosumator este inregistrata ca atribut al CF in POSF.

**Comment by bogdannedelcu** [comment]
Ref 15: Situatia descrisa este similara cu cea a incheierii a 2 contracte simultan la ghiseele a 2 furnizori diferiti. Ambele sisteme vor emite mesaje care vor fi transmise de POSF catre Operatorul de retea. In sistemul operatorului s-ar putea face verificarea existentei simultane a 2 contracte active pe locul de consum.

**Comment by bogdannedelcu** [comment]
Ref 18: Articolul respectiv se refera la personalul desemnat de F sa asigure activitatile privind contractarea/schimbarea prin intermediul POSF, astfel incat F sa respecte obligatiile stabilite de reglementari. Pentru fiecare categorie de personal implicat F stabileste (prin selectie) drepturile in cadrul platformei (tehnice/IT, semnare contracte, verificarea si validare documente etc.)
