### ISSUE TITLE
 Credentiale diferite pentru BROKER si WEB pentru același actor

### ISSUE THREAD

**Issue by schimbare-furnizor** [posfgit/standard#174]
Buna ziua,

Datele migrate prin API BROKER POSF in mediul de staging (https://posf-staging.anre.ro/auth/realms/BROKER/account/#/)
pot fi vizualizate/modificate in WEB POSF in mediul de staging (https://posf-staging.anre.ro/)
ținând cont ca
pentru BROKER user=tulceagaz_oper_gn  si
pentru WEB user= schimbare-furnizor@tulceagaz.ro
si parolele diferite.
( credentiale diferite pentru BROKER si WEB pentru același actor ).

Asteptam cu interes un raspuns din partea dvs.

**Comment by bogdannedelcu** [comment]
care este intrebarea? Sunt conturi de acces diferite pentur API si pentru Web, primul este destinat comunicatiei intre programe, al doilea este pentru oameni.

**Comment by schimbare-furnizor** [comment]
Datele migrate prin API BROKER POSF pot fi vizualizate si modificate in WEB POSF ?
