### ISSUE TITLE
Index autocitit 

### ISSUE THREAD

**Issue by DEERClaudiaPOPESCU** [posfgit/standard#175]
Buna ziua,

Avand in vedere obligatia CF de a furniza indexul autocitit la initierea procedurii de SF ( art.5 lit. a) si 23 lit. b) din Regulament), respectiv a Furnizorului de a intermedia transmiterea acestui index platformei POSF (art.34 b), si avand in vedere prevederile art. 34 (4) lit. d), respectiv ale art. 43 (1) lit. e) din Regulament, va rugam sa ne precizati prin intermediul carui tip de mesaj va fi transmis acest index catre OR.
 
De asemenea, prin intermediul carui tip de mesaj va fi transmis catre OR eventualul index autocitit aferent datei efective de schimbare a furnizorului (art.25 lit e) din Regulament) transmis de catre CF direct in POSF (sau prin intermediul Furnizorului in cazul incheierii contractului inafara POSF).

Multumesc. 
Echipa DEER

**Comment by BadiuAlexandru** [comment]
Buna ziua,

Se poate primi un raspuns aici?

**Comment by DEERClaudiaPOPESCU** [comment]
Revin cu rugamintea unui raspuns la aceasta intrebare.

In acelasi timp vin cu o erata privind numarul primului articol de lege invocat mai sus, si anume in loc de _art.5 lit. a)_, rog a se citi _**art.15 pct.5 lit. a)**_ 

Multumesc.
Echipa DEER

**Comment by bogdannedelcu** [comment]
Mesajele ContractSignedByClient si ContractSignedBySupplier trebuie sa contina obligatoriu indexul autocitit.
OR trimite index prin ContractNetworkChangedInfo
