### ISSUE TITLE
Status: 500 "No message available"

### ISSUE THREAD

**Issue by pcs-cuore** [posfgit/standard#179]
La POST-ul pentru sincronizare a contractului primim raspunsul: 

~~~
{
    "path": "/broker/postMessage",
    "error": "Internal Server Error",
    "status": 500,
    "message": "No message available",
    "timestamp": "2022-10-21T07:17:22.71+00:00"
}
~~~

[payload-sync.txt](https://github.com/posfgit/standard/files/9837035/payload-sync.txt)

**Comment by costinpahontu** [comment]
solved .  Dar sa stii ca oricum nu trimiti bine . trimiti un CLC la un operator de EE
