### ISSUE TITLE
Mesaj de notificare pentru locurile de consum la care expira contractul de furnizare

### ISSUE THREAD

**Issue by ConsuelaKozmaDEGR** [posfgit/standard#181]
@bogdannedelcu  Operatorul DelgazGrid integrat prin API solicita transmiterea automata de notificari zilnice care sa contina informatiile legate de locul de consum si de data expirarii contractului de furnizare.  Solicitarea noastra se justifica avand in vedere volumul mare al locurilor de consum care ajung la final de contract de furnizare, de faptul ca nu dispunem de informatia privind data de final de contract de furnizare si de asemenea de faptul  ca restul proeselor sunt automatizate.

**Comment by bogdannedelcu** [comment]
Au fost introduse tipuri de mesaje noi pentru aceste situatii Notification*

https://github.com/posfgit/standard#mesaje-de-tip-notificare-intre-partile-unui-contract
