### ISSUE TITLE
Introducere contracte existente in webPOSF

### ISSUE THREAD

**Issue by Plenerg** [posfgit/standard#186]
Buna ziua, 
Va rugam sa ne ajutati in gasirea machetelor XLSX, XSD in care trebuie incarcate datele pentru contractele existente in portofoliu cu scopul de a creea fisierul XML asa cum este sugerat in link-ul atasat. https://github.com/posfgit/standard/tree/main/samples/small-company.
Deoarece suntem un furnizor mic (avem un singur contract de furnizare) nu avem posibilitatea de a integra cu un broker API. Dorim introducerea contractului existent pe cale MANUALA.

Va multumim!

**Comment by bogdannedelcu** [comment]
Puteti folositi aplicatia WebPOSF daca aveti putine contracte https://posf.ro/inregistrare

**Comment by EnergyGas** [comment]
Buna ziua,
in linkul de mai jos https://github.com/posfgit/standard/tree/main/samples/small-company regasim aceste indrumari

"Un caz de utilizare simplu ar fi ca furnizorii si operatorii care doresc sa incarce contracte sau locuri de consum existente s-ar rezuma astfel:
Se va crea cate un fisier XML pentru fiecare contract cu structura de mesaj definita in standard
Se copiaza fisierul XML in directorul IN
Sa lanseze programul execute-java-send.bat care transmite mesajele in POSF.
Programul citeste fisier cu fisier, le transmite in API POSF folosind user/parola si salveaza rezultatul in directorul OUT"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Din pacate nu toti cei care vom lucra in web posf avem cunostinte de cod si atunci , ne-ar ajuta concret sa stim ce avem de facut, astfel incat sa avem toate contractele existente introduse in web posf : 
- unde regasim structura de mesaj
- user /parola folosite vor fi cele introduse la logarea in web posf?
- pentru cei care nu avem cunostinte de cod, ar fi mult mai simplu ca incarcarea contractelor existente sa o realizam din interfata contului din web posf, unde sa regasim o zona de import in masa a tuturor contractelor existente fie in excel fie xml !!!, eventual sa avem un model de fisier pe care sa il mapam cu datele din contracte pe care ulterior sa il incarcam in interfata web
Multumesc!

**Comment by bogdannedelcu** [comment]
Solicitati user/parola la servicedesk@anre.ro pentru API staging si productie, veti putea incarca repede fisierele XML. Nu exista in interfata web posibilitatea incarcarii in masa, doar prin programul small-company.
