### ISSUE TITLE
Endpointul /broker/profile raspunde cu TIMEOUT pentru un anumit user

### ISSUE THREAD

**Issue by pcs-cuore** [posfgit/standard#188]
Endpointul https://posf.ro/broker/profile raspunde cu 504 Gateway Time-out doar pentru utilizatorul eft_furniz_ee

Pentru alte conturi aduce raspunsul corect in timp util.

Va rugam sa ne ajutati sa deblocam.

**Comment by pcs-cuore** [comment]
Acelasi lucru se intampla si in mediul de staging cu userul eft_furnizare_srl .

Endpointul de obtinere token functioneaza, dar https://posf.ro/broker/profile si https://posf-beta.anre.ro/broker/profile raspund cu 504 pentru ambele conturi in ambele medii.

**Comment by pcs-cuore** [comment]
Raspuns endpoing
~~~
<html>

<head>
	<title>504 Gateway Time-out</title>
</head>

<body>
	<center>
		<h1>504 Gateway Time-out</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>

</html>
~~~

**Comment by bogdannedelcu** [comment]
s-a rezolvat
