### ISSUE TITLE
Reason operator != place operator

### ISSUE THREAD

**Issue by AndreiKa13** [posfgit/standard#190]
Am rugaminte sa ne transmiteti motivele sau cauza pentru care puntru unele contracte de furnizare transmise in sistem folosind mesajul **ContractChangedInfo** primim motivul **operator != place operator**.  Multumesc!

**Comment by bogdannedelcu** [comment]
pentru ca pe mesajul respectiv operator.id difera de place.operator.id, trebuie sa fie acelasi operator cel pe care il mentionati in contract cu cel care are locul de consum. Trimiteti un exemplu de mesaj aici va rog daca nu e clar
