### ISSUE TITLE
Conventie de consum si date ID

### ISSUE THREAD

**Issue by bogdanmate** [posfgit/standard#2]
1. Ref la schema publicata, incheierea conventiei de consum poate fi mai rapida. Aceasta ajunge in POSF si la OR odata cu datele noului contract. OR ar trebui sa trimita mesaj inapoi numai daca are obiectii. Daca nu are, trebuie mers pe acceptare tacita.
2. Datele de identificare ale CF si ale locului de consum: Criteriile de validare la primirea in POSF trebuie sa fie eficiente si simple intrucat aceeasi adresa se poate scrie in multe feluri, dar asta nu trebuie sa fie criteriu de respingere (de ex. Ion Agarbiceanu vs Agirbiceanu Ion)

**Comment by bogdannedelcu** [comment]
Buna ziua si multumesc pentru comentariu, o sa raspund punct cu punct:

1. Schema prezentata este cu titlu de concept, fluxul descris nu este conform cu regulamentul, doar prezinta din punct de vedere tehnic actorii implicati si abordarea asincrona a schimbului de mesaje. Am pus aceasta mentiune si pe prima pagina.
Retinem observatia acceptarii tacite ca fiind utila.

2. De acord cu propunerea, criteriile de validare incercam sa fie incluse in schmea care descrie mesajul astfel incat sa se poata face validarea chiar la cel care il publica, verificand bineinteles si la receptie. Vom reveni cu actualizari pe fiecare camp propus in sectiunea de comentarii din XSD.
