### ISSUE TITLE
Endpointul own/readMessage raspunde cu un html

### ISSUE THREAD

**Issue by pcs-cuore** [posfgit/standard#206]
Endpointul https://posf.ro/own/readMessage?consumerId=1c6a3c73-be87-4368-a3ea-0cbf7de1f392 raspunde cu un html.

1c6a3c73-be87-4368-a3ea-0cbf7de1f392 este id-ul mesajului obtinut din endpointul refused
```
{
            "brokerId": 67510947,
            "authorId": "0015bfe6-036a-4553-b87c-7d6a8c0519df",
            "messageId": "1c6a3c73-be87-4368-a3ea-0cbf7de1f392",
            "timestamp": "2022-11-15T19:44:51.422086Z",
            "type": "ContractChangedInfo",
            "reason": "place not found"
        }
```

Pe request header trimitem 

~~~
Content-Type: application/json
Accept: application/json
~~~

Pe response header primim

~~~
Content-Type: text/html
~~~

Raspuns html: 
[Response-own-read-message.txt](https://github.com/posfgit/standard/files/10084773/Response-own-read-message.txt)

**Comment by bogdannedelcu** [comment]
folositi url /broker/own/readMessage, altfel ajungeti in aplicatia WebPOSF
