### ISSUE TITLE
Contract nou adaugat de client final, pe un loc de consum se duce in Cereri cu statusul Draft

### ISSUE THREAD

**Issue by pcs-cuore** [posfgit/standard#245]
Contract nou adaugat de client final, pe un loc de consum se duce in Cereri cu statusul Draft

Mediu: Staging

Pasi de reproducere:
1. Se adauga un loc de consum in webposf in contul Distribuitorului
2. Se adauga o oferta in webposf-comparator-furnizori in contul Furnizorului
3. Se asociaza locul de consum de la pasul 1 in contul Clientului Final
4. Din Optiuni se Adauga un contract nou pe locul de consum si se parcurge tot Wizzardul cu succes

Rezultat: Un entry nou in tabul Cereri cu statusul Draft dar niciun mesaj CSBS in brokerul furnizorului

PS:
1. Pe acel loc de consum a mai existat un contract cu statusul INCETAT inainte de a adauga clientul final contractul sau
2. Numarul noului contract Draft este 896485
3. CLC-ul locului de consum este Test12345
4. Codul ofertei este METCASNICIGN211222

**Comment by madalinalixandra** [comment]
Comportamentul este normal, atunci cand CF trimite cererea de contract spre FN, nu se trimite CSBS, ci CSBC.
Dupa ce cererea a ajuns la FN, acesta poate sa solicite informatii suplimentare si sa emita ContractMoreInfo sau sa valideze cererea si sa emita CSBS.

**Comment by pcs-cuore** [comment]
Voiam sa zic CSBC, am gresit, dar queue-ul de broker e gol.

**Comment by madalinalixandra** [comment]
Ce companie reprezentati si in ce calitate, furnizor?
Este de ajutor cand postati astfel de tickete sa mentionati si compania si calitatea (furnizor/operator).

**Comment by costinpahontu** [comment]
Am verificat si mesajul a ajuns corect in cozile 0015bfe6-036a-4553-b87c-7d6a8c0519df si 749e2e6f-7c83-42fb-a2be-3f3b168b891d.  Insa din ce observ nu aveti nici un consumer pentru ele deci practic nu pare ca cititi .

**Comment by costinpahontu** [comment]
da. conturi de broker asociate la  Furnizor MET si Operator InstantConstruct pentru cozile alea .

**Comment by pcs-cuore** [comment]
MET:
User webposf: [customer.care@met.com](mailto:customer.care@met.com)
User broker: met_energy_furnizor_ee_gn

InstantConstruct:
User webposf: [office@icc20.ro](mailto:office@icc20.ro)
User broker: instant_construct_operator_gn


De ce contul de webposf nu este legat de contul de broker? Intreb sa stiu pe viitor sa nu ma trezesc in aceeasi situatie.

**Comment by NocodeProcesio** [comment]
@costinpahontu - conturile API POSF Staging pe care le folosim sunt cele pe care le avem de la echipa POSF.
Te rog sa ne clarifici ce avem noi de facut sau cine ce trebuie sa faca ce pentru a debloca aceasta situatie. Multumesc.

Listez mai jos toti FZ si OD pentru care avem credentiale API Staging POSF - pentru care avem nevoie ca acestea sa functioneze si sa fie conectate la cozile de mesaje:

1. MET
2. Intant Construct (FZ & OD)
3. NOVA (FZ & OD)
4. Romgaz (FZ & OD) 
5. EOL
6. Entrex
7. EFT
8. QMB Energ
9. Veolia
10. Oligopol (FZ & OD)
11. AFI

**Comment by costinpahontu** [comment]
#met - ar trebui aveti 2 conturi asa cum aveti si in productie . contul met_energy_furnizor_ee_gn(3ce429af-436e-4e1b-abf2-0ffb7b09437b) este asociat furnizor ee.  Acolo pare ca cititi din coada . 

ar mai trebui sa aveti un cont legat la furnizor gn - pentru a fi legat la 0015bfe6-036a-4553-b87c-7d6a8c0519df (o sa intreb la service desk pentru a verifica din ce cauza e asa )

#InstantConstruct  - este legat la ce trebui (749e2e6f-7c83-42fb-a2be-3f3b168b891d) insa nu pare ca cititi cu poolMessage sau read/commit .  va rog sa verificati daca apelati aceste api-urile cu acest cont si nu cu altul.

**Comment by NocodeProcesio** [comment]
Multumim frumos @costinpahontu - legat de credentiale. La MET - impreuna cu MET am ridicat recent (~ 1 saptamana) ticket pentru a re-obtine credentialele API Staging si ni s-a raspuns ca sunt acestea pe care le-a mentionat colegul meu.

Acum este clar ca nu sunt de ajuns - trebuie sa fie o oglinda a mediului de productie (si noi ne-am mirat ca este doar unul).

Asa ca vin cu requestul de a ne ajuta cu toate credentialele necesare pentru mediul de test pentru toti clientii mentionati mai sus.

Apeciez ajutorul!
