### ISSUE TITLE
furnizare detalii tehnice POSF

### ISSUE THREAD

**Issue by florinser** [posfgit/standard#3]
Buna ziua, 
Multumim pentru informatiile transmise. Pe baza acestor informatii intelegem principiile de functionarea ale platformei in linii mari. 
Insa, pentru a formula un punct de vedere si a contribui la acest demers prin furnizarea de observatii/comentarii/validare, conform solicitarii dvs., este necesar sa intelegem mai in detaliu modul de functionare al platformei. 
In acest sens, ne puteti spune daca si cand putem avea acces la documentul de specificatii prezentat in cadrul intalnirii? Acest document ne va ajuta sa intelegem mai bine modul de functionare al platformei , fluxurile de date, continutul mesajelor, intervalele de transmitere si mecanismele de error handling, informatii pe baza carora putem oferi un feedback concret.

Aditional, mentionam ca am analizat schema de ansamblu pusa la dispozitie si avem urmatoarele intrebari/observatii:
1) Intrucat tipul de comunicare intre platforme va fi de tip asincron, ne puteti spune estimativ care vor fi termenele de procesare pentru mesajele prevazute ? (minute, ore, zile)
2) Atat timp cat comunicarea va fi de tip asicron si avand in vedere ca un client poate initia mai multe cereri pentru acelasi loc de consum in dorinta de contracta rapid (in platforma POSF, in platforma Furnizorilor),
 va rugam sa mentionati cum va fi tratata o astfel de situatie in cadrul platformei POSF, astfel incat sa nu apara inconsistente in prelucrare datelor ? 

Multumesc,

**Comment by bogdannedelcu** [comment]
Buna ziua, raspund punctual cu mentiunea ca vom reveni cu o noua versiune care va clarifica toate punctele ridicate.

1. Mesajele se vor inregistra in logul de mesaje POSF si in baza de date in termen de cateva secunde. Procesarile automate care vor genera alte evenimente si alte mesaje catre terti se vor efectua in termen de cateva minute in functie de incarcarea sistemului si de complexitatea logicii.
2. In platforma WebPOSF vom retine mentiunea in sensul ca vom limita numarul de cereri concurente pe care poate lucra un client la una. Mesajul transmis catre broker-ul POSF va fi transmis doar la finalizarea completarii cererii, nu si cat timp este in draft, responsabilitatea unicitatii fiind la WebPOSF. Cat priveste sistemul Furnizorilor, vor trebui implementate astfel de restrictii asa incat sa previna dublarea lor. Retinem nevoia unor verificari suplimentare si in platforma POSF pentru cazuri de dublare.

**Comment by acristea23** [comment]
Buna ziua, Ne puteti spune cand putem avea acces la documentul de specificatii prezentat in cadrul intalnirii?

**Comment by bogdannedelcu** [comment]
Buna ziua, am publicat detaliile din documentul prezentat in cadrul sedintei direct in pagina Readme.md https://github.com/posfgit/standard. Va recomand sa folositi functionalitatea Watch (coltul dreapta sus) a repository-ului Git pentru a fi informat de schimbarile aparute. De asemenea puteti regasi aici https://github.com/posfgit/standard/tree/main/samples/python un sample de API de publicat/citit mesaje pe care il puteti descarca pentru teste.

Pentru orice fel de observatii/sugestii va rog sa postati in cadrul sectiunii Issues

**Comment by axinitza** [comment]
Buna ziua. In exemplul dumeavoasta am observat ca folositi Kafka iar la prezentarea Tehnica din 24.02 a fost vehiculat alt servar de mesaje MQ. Dorim sa stim care din cele 2 o sa fie folosita astfel incat sa analizam metoda de integrare (ce client sa folosit). Daca considerati ca detaliile tenice nu pot fi publicate aici am rugamintea sa imi comunicati. Multumesc.

**Comment by bogdannedelcu** [comment]
@axinitza va ramane Kafka ca si tehnologie de stocaree a mesajelor in timp ce schimbul de mesaje se va face prin aceste API REST care vor permite transferul de mesaje in format XML sau JSON. In masura in care doriti si alte modalitati de schimb de mesaje, suplimentar fata de API REST, va rog sa ne propuneti si vom analiza.

**Comment by axinitza** [comment]
Shimbul de mesaje prin API REST format XML sau JSON este foarte bun, dar cum se va face transferul de mesaje, POSF o sa expuna toate interfetele atat de IN cat si de OUT si Furnizorul verifica din cand in cand sau Furnizorul trebuie sa expuna si el interfete catre POFS ?  

In prezentare Tehnica sa vehivulat ActiveMQ si daca exista posibilitatea conectarii direct la servarul de MQ astfel incat sa consuman/publicam noi mesajele din/in cozi era o comunicatie mai directa, aceasta optiune mai este valabila (chiar daca este Kafka) ?

**Comment by bogdannedelcu** [comment]
POSF va expune interfetele REST pentru publicare si citire de mesaje din cozi pentru fiecare furnizor/operator asa cum sunt prezentate in sample https://github.com/posfgit/standard/tree/main/samples/python.

Furnizorul publica sau interogheaza periodic pentru a primi mesaje. Furnizorul/operatorul NU trebuie sa expuna interfete, mesajele se vor regasi in cozile POSF pentru citire, fiind persistate pe termen nelimitat, fara a fi sterse la citire. 

Motivul pentru care am optat pentru Kafka (topics) versus ActiveMQ (queues) este sa dam posibilitatea furnizorilor sa poata reciti toate mesajele lor, in cazul in care se doreste o reprocesare. 

In imaginea de mai jos regasiti strategia de publicare/citire mesaje din topic Kafka, cu mentiunea ca API /broker va ascunde din aceasta complexitate oferind furnizorilor acces la ultimul mesaj din coada in mod implicit, iar daca se solicita in mod special se vor putea crea noi consumatori care sa consume mesajele de la inceputul topicului.

![image](https://user-images.githubusercontent.com/8427812/158772351-62b8ac4d-9e0c-4f3d-b145-c1e9c76bacda.png)

**Comment by axinitza** [comment]
Multumesc pentru explicatii, lucrurile sunt mult mai clare.
