### ISSUE TITLE
Detalii migrare

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#56]
Buna ziua, va rog sa ne confirmati ca nu este nevoie sa completam campul adaugat astazi **counterIndexInterval** la migrarea locurilor de consum prin fluxul PlaceUpdatedByOperator.

**Comment by EDistributie** [comment]
@bogdannedelcu 
Conform raspunsului de mai jos, elementul Consumption nu trebuie trimis, fiind optional.
![image](https://user-images.githubusercontent.com/103568621/176674405-5e3c95ae-9c40-44dd-9df0-b2c55a00bce8.png)

Insa, conform imaginilor de mai jos, elementul ConsumptionItem cu subcampurile month si value sunt obligatorii. 
Puteti corecta eliminarea obligativitatii completarii campurilor?
![image](https://user-images.githubusercontent.com/103568621/176674708-dd293a79-635b-410c-ba4f-86173f31d159.png)

![image](https://user-images.githubusercontent.com/103568621/176674491-3c8d4d41-25a4-488c-901b-238824f64f23.png)

**Comment by bogdannedelcu** [comment]
Consumption si ConsumptionItem nu sunt obligatorii conform schemei XSD, nu trebuie sa puna probleme daca nu il trimiteti. Nu trebuie sa lasati tag-ul XML gol, trebuie eliminat complet din mesaj.

exemplu:

```
<?xml version="1.0" encoding="UTF-8"?>
<anre:TechnicalData xmlns:anre="http://www.anre.ro/ANRESchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.anre.ro/ANRESchema file:/E:/CloudStation/!TNI/ANRE/standard/ANRESchema.xsd">
    <counterIndexDesc>counterIndexDesc0</counterIndexDesc>
    <counterIndexInterval>0</counterIndexInterval>
    <counterIndexReadDate>2006-05-04</counterIndexReadDate>
    <counterIndexValue>counterIndexValue0</counterIndexValue>
    <counterSeries>counterSeries0</counterSeries>
    <counterType>ACTIVE</counterType>
    <date>2006-05-04</date>
    <documentType>ACORDACCES</documentType>
    <number>number0</number>
    <smartMeter>false</smartMeter>
    <status>CONECTAT</status>
    <type>type0</type>
</anre:TechnicalData>
```

**Comment by EDistributie** [comment]
@bogdannedelcu  puteti raspunde pct 1? Multumesc!

**Comment by bogdannedelcu** [comment]
> Buna ziua, va rog sa ne confirmati ca nu este nevoie sa completam campul adaugat astazi **counterIndexInterval** la migrarea locurilor de consum prin fluxul PlaceUpdatedByOperator.

Confirmam

**Comment by EDistributie** [comment]
Multumim!
