### ISSUE TITLE
ExecutionAddress & Place

### ISSUE THREAD

**Issue by GabrielaFlorescu** [posfgit/standard#57]
1. Va rog sa ne spuneti daca noi trebuie sa trimitem cate un mesaj ContractSignedbySupplier (after GoLive) sau ContractChangedInfo (pt migrarea initiala) pentru fiecare Place/loc de consum? According to xsd, noi intelegem ca in Contract trebuie sa trimitem un singur Place?

2. In relatie cu intrebarea 1, ati spus ca executionAddress se va completa identic cu Address din locul de consum - ce se intampla daca avem mai multe Places, ce trecem la executionAddress?

**Comment by bogdannedelcu** [comment]
> 1. Va rog sa ne spuneti daca noi trebuie sa trimitem cate un mesaj ContractSignedbySupplier (after GoLive) sau ContractChangedInfo (pt migrarea initiala) pentru fiecare Place/loc de consum? According to xsd, noi intelegem ca in Contract trebuie sa trimitem un singur Place?



> 1. Va rog sa ne spuneti daca noi trebuie sa trimitem cate un mesaj ContractSignedbySupplier (after GoLive) sau ContractChangedInfo (pt migrarea initiala) pentru fiecare Place/loc de consum? According to xsd, noi intelegem ca in Contract trebuie sa trimitem un singur Place?
> 2. In relatie cu intrebarea 1, ati spus ca executionAddress se va completa identic cu Address din locul de consum - ce se intampla daca avem mai multe Places, ce trecem la executionAddress?



> 1. Va rog sa ne spuneti daca noi trebuie sa trimitem cate un mesaj ContractSignedbySupplier (after GoLive) sau ContractChangedInfo (pt migrarea initiala) pentru fiecare Place/loc de consum? According to xsd, noi intelegem ca in Contract trebuie sa trimitem un singur Place?

Inainte de golive trimiteti ContractChangedInfo iar apoi orice contract nou semnat trimiteti ContractSignedBySupplier. Cate unul pentru fiecare place, daca cumva aveti contracte cu mai multe Place inauntru atunci trimiteti mesaje distincte, ID contract acelasi , ID corelare unic.
