### ISSUE TITLE
Probleme tehnice API

### ISSUE THREAD

**Issue by Frizi20** [posfgit/standard#59]
Buna ziua, sunt Matac Cristi de la Renovatio Trading. 

De o zi, orice request catre https://posf-beta.anre.ro/auth/realms/BROKER/protocol/openid-connect/token imi da ca raspuns:
{"error":"unknown_error"}. Ne puteti transmite care este cauza acestei probleme si daca puteti estima cand se va remedia ?

**Comment by bogdannedelcu** [comment]
a fost o problema de indisponibilitate a platformei
