### ISSUE TITLE
Intalnire cu ANRE 05.07.2022

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#60]
@bogdannedelcu Ne poti pune la dispozitie inregistrarea intalnirii de astazi?
Multumesc!

**Comment by bogdannedelcu** [comment]
https://drive.google.com/file/d/1Ses7ETWtbTz9Pea9gCZXCW-43GzJSCdm/view?usp=sharing

**Comment by GabrielaFlorescu** [comment]
@bogdannedelcu 
va rugam sa ne puneti la dispozitie diagrama de proces prezentata in inregistrare (pe care nu am vazut-o pana acum si a fost ilizibila in inregistrare)
