### ISSUE TITLE
eroare autentificare API 

### ISSUE THREAD

**Issue by andreeamojoiu** [posfgit/standard#61]
La incercarea de autentificare prin API si obtinere token, dupa 10 secunde, se primeste eroarea "500 Unexcepted error".
La incercarea de logare in browser pe linkul https://posf-beta.anre.ro/auth/realms/BROKER/account/se obtine eroarea "Unexpected error when handling authentication request to identity provider"

**Comment by bogdannedelcu** [comment]
a fost o perioada de indisponibilitate a mediului de test. Daca se reproduce va rugam sa comunicati.
