### ISSUE TITLE
Intrebari discutie 05.07

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#62]
Referitor la discuta avuta in 05.07.2022 cu privire la necesitatea transmiterii tipului de tarif (Tip pret) ales de client prin POSF si pentru care a ramas ca ne transmiteti un raspuns, va rugam sa mai luati o data in calcul, ca pe langa tarif, din POSF sa fie transmise si:

- Tipul de client (casnic/noncasnic);
- Tipul de oferta, avand in vedere ca exista 2 variante: servicul universal sau piata concurentiala;
- Numarul de schimburi in care lucreaza clientul final: incarcarea procentuala pe schimburi fata de schimbul I (100 %) asa cum sunt definite in Ordinul ANRE 25/2021 si care sunt folosite pentru calculul pierderilor de energie pentru locurile unde punctul de delimitare nu coincide cu punctul de masura: a) schimbul II: .................. %; b) schimbul III: .................. %

In prezent pe site-ul ANRE in sectiunea „comparator-de-tarife” sunt afisate/solicitate informatii cu privire la „Tip client” (valori casnic/noncasnic); Tip oferta (Oferte concurentiale/Oferte serviciul universal); Tip pret (Nediferentiat/Diferentiat pe zone orare). Similar se pot prelua si in POSF aceste informatii?

Aceste date sunt necesare pentru programarea contorului conform cu tariful ales de client si pentru facturarea corecta a energiei consumate (energie activa si pierderi, daca este cazul).

Exemplu din comparator de tarife existent pe site-ul ANRE:
![image](https://user-images.githubusercontent.com/103568621/177515714-e29f41b5-daa8-45a3-9461-ee1fce77369b.png)
![image](https://user-images.githubusercontent.com/103568621/177515792-08530da7-47b2-406d-99c1-13e5b697f3c8.png)
![image](https://user-images.githubusercontent.com/103568621/177515848-a78e829e-c5df-45a9-8b3e-ba7f1b63e95b.png)

**Comment by EDistributie** [comment]
@bogdannedelcu puteti raspunde va rog ? Multumesc!

**Comment by bogdannedelcu** [comment]
> ContractMoreInfo --> Va rugam sa ne confirmati daca OR va avea posibilitatea de a transmite fluxuri prin care sa solicite mai multe informatii, asa cum furnizorul are posibilitatea de a cere informatii prin acest flux ![image](https://user-images.githubusercontent.com/103568621/177542626-7d774daf-044e-4ed3-b839-5bf8a613d416.png)

OR nu are posibilitatea de a solicita mai multe informatii prin POSF

**Comment by bogdannedelcu** [comment]
Referitor la informatiile din oferta revenim cu o clarificare pe stadnard
