### ISSUE TITLE
ContractNetworkChangedInfo pt OR

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#66]
Fluxul ContractNetworkChangedInfo ce trebuie transmis de OR cand se adauga un nou loc de consum in cadrul contractului cu un anumit furnizor (cand se finalizeaza cererea creata prin fluxul ContractSignedBySupplier), contine elementele "Contract" si "Info" . Va rog sa ne spuneti daca este corecta intelegerea noastra:
In campurile din sectiunea "contract" 
- additionalDate (Data act aditional)  si additionalNumber (Numar act aditional) completam cu actele aditionale intre OR si furnizor valori ale distribuitorului (OR) 
- number = numarul de contract intre OR si furnizor 
- counterIndexReadDate si counterIndexValue [si/sau counterSeries (in cazul inlocuirilor de contor) ; si/sau smartMeter] completam cu valorile de la executia in teren a cererii creata prin fluxul ContractSignedBySupplier , valori ce pot fi diferite de valorile primite in fluxul initial ContractSignedBySupplier

In campul "info" vom completa cu textul "cerere finalizata"

**Comment by EDistributie** [comment]
@bogdannedelcu puteti raspunde va rog ? Multumesc!

**Comment by bogdannedelcu** [comment]
> additionalDate (Data act aditional) si additionalNumber (Numar act aditional) completam cu actele aditionale intre OR si furnizor valori ale distribuitorului (OR)

Confirmam, se completeaza doar daca aceste modificari se efectueaza prin act aditional. Daca nu se fac prin act aditional nu se completeaza.

**Comment by bogdannedelcu** [comment]
> * number = numarul de contract intre OR si furnizor

Pentru cazul in care este vorba de contract intre furnizor si OR, daca este contract de retea direct cu clientul final atunci este numarul acelui contract.

**Comment by bogdannedelcu** [comment]
> * counterIndexReadDate si counterIndexValue [si/sau counterSeries (in cazul inlocuirilor de contor) ; si/sau smartMeter] completam cu valorile de la executia in teren a cererii creata prin fluxul ContractSignedBySupplier , valori ce pot fi diferite de valorile primite in fluxul initial ContractSignedBySupplier

Intr-adevar este posibil sa fie valori diferite

**Comment by bogdannedelcu** [comment]
> In campul "info" vom completa cu textul "cerere finalizata"

de acord

**Comment by EDistributie** [comment]
Multumim! Acum este clar
