### ISSUE TITLE
Acte aditionale contracte de furnizare

### ISSUE THREAD

**Issue by GabrielaFlorescu** [posfgit/standard#76]
In cazul in care pentru un client avem un contract si 10 acte aditionale, la migrarea initiala trebuie sa trimitem doar cel mai recent act aditional, adica cel care este in vigoare la momentul migrarii, corect?

**Comment by bogdannedelcu** [comment]
Se trimite ultimul act pentru fiecare loc de consum.

**Comment by ItSupportRenovatioTrading** [comment]
1. Ca principiu, ca sa verificam ca interpretam corect, initial transmitem metadatele de contract actualizate cu toate modificarile (curent valabile) din toate actele aditionale , urmand ca la primul act aditional ulterior migrarii initiale sa transmitem `ContractChangedInfo` in care sa completam metadatele actului aditional.

2. Mesajul `ContractChangedInfo` va avea ca si `CorrelationId` Id-ul mesajului initial `ContractChangedInfo` ?
3. In cazul in care e corecta interpretarea de la pct 2, se aplica la fel si in cazul mesajelor de modificare contracte inregistrate anterior in POSF prin unul dintre tipurile `ContractSignedBySupplier`, `ContractSignedByClient` ... etc ?
