### ISSUE TITLE
ContactAddress - email

### ISSUE THREAD

**Issue by GabrielaFlorescu** [posfgit/standard#79]
Pentru un contract semnat in POSF, FZ nou primeste pe elementul Contract: 
- datele clientului Company contactAddress/email
- Legalrepresentative/Person cu contactAddress/email si
- CorrespondenceClientContactAddress cu contactAddress/email 

Daca electronicinvoice este YES, noi de unde stim pe care dintre aceste adrese de email trebuie sa trimitem factura?

**Comment by bogdannedelcu** [comment]
campul "correspondenceClientContactAddress" a fost prevazut pe contract astfel incat sa fie explicit declarat ca fiind adresa de corespondenta a clientului asociata cu locul de consum. Adresa ce poate fi diferita de adresele companiei sau a persoanelor.

**Comment by GabrielaFlorescu** [comment]
Multumesc.
