### ISSUE TITLE
> > 1. Confirmare a faptului ca se va putea furniza acces  in interfata web POSF si operatorilor/furnizorilor care se vor integra prin API. Este necesara conform discutiei si o gestiune manuala a unui set de mesaje rar utilizate si offline.   deadline **07.07.2022**

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#88]
> > 1. Confirmare a faptului ca se va putea furniza acces  in interfata web POSF si operatorilor/furnizorilor care se vor integra prin API. Este necesara conform discutiei si o gestiune manuala a unui set de mesaje rar utilizate si offline.   deadline **07.07.2022**
> 
> Aceasta facilitate nu a fost prevazuta dar vom tine cont de cerinta dvs si vom gasi o solutie tehnica pentru a o satisface.

@bogdannedelcu aveti noutati asupra cerintei ?

_Originally posted by @EDistributie in https://github.com/posfgit/standard/issues/63#issuecomment-1196865591_

**Comment by EDistributie** [comment]
@bogdannedelcu in cazul unui raspuns afirmativ asupra cerintei de mai sus, puteti lua in calcul incarcarea/descarcarea de fisiere masive specifice fluxurilor POSF (pentru modulul Operator fara integrarea cu API). Multumesc

**Comment by bogdannedelcu** [comment]
> @bogdannedelcu in cazul unui raspuns afirmativ asupra cerintei de mai sus, puteti lua in calcul incarcarea/descarcarea de fisiere masive specifice fluxurilor POSF (pentru modulul Operator fara integrarea cu API). Multumesc

se poate folosi acest program pentru incarcare / descarcare de mesaje, dar e nevoie de un cont de acces API
https://github.com/posfgit/standard/tree/main/samples/small-company

**Comment by bogdannedelcu** [comment]
> > > 1. Confirmare a faptului ca se va putea furniza acces  in interfata web POSF si operatorilor/furnizorilor care se vor integra prin API. Este necesara conform discutiei si o gestiune manuala a unui set de mesaje rar utilizate si offline.   deadline **07.07.2022**
> > 
> > 
> > Aceasta facilitate nu a fost prevazuta dar vom tine cont de cerinta dvs si vom gasi o solutie tehnica pentru a o satisface.
> 
> @bogdannedelcu aveti noutati asupra cerintei ?
> 
> _Originally posted by @EDistributie in [#63 (comment)](https://github.com/posfgit/standard/issues/63#issuecomment-1196865591)_

Nu vom limita accesul la interfata WebPOSF a furnizorilor/operatorilor care au acces prin API dar consideram ca este riscant sa o folositi deoarece mesajele trimise publicate prin interfata Web nu vor putea fi accesate prin API. Lucram la o solutie pentru acest inconvenient.

**Comment by EDistributie** [comment]
> > > > 1. Confirmare a faptului ca se va putea furniza acces  in interfata web POSF si operatorilor/furnizorilor care se vor integra prin API. Este necesara conform discutiei si o gestiune manuala a unui set de mesaje rar utilizate si offline.   deadline **07.07.2022**
> > > 
> > > 
> > > Aceasta facilitate nu a fost prevazuta dar vom tine cont de cerinta dvs si vom gasi o solutie tehnica pentru a o satisface.
> > 
> > 
> > @bogdannedelcu aveti noutati asupra cerintei ?
> > _Originally posted by @EDistributie in [#63 (comment)](https://github.com/posfgit/standard/issues/63#issuecomment-1196865591)_
> 
> Nu vom limita accesul la interfata WebPOSF a furnizorilor/operatorilor care au acces prin API dar consideram ca este riscant sa o folositi deoarece mesajele trimise publicate prin interfata Web nu vor putea fi accesate prin API. Lucram la o solutie pentru acest inconvenient.

De exemplu: in cazul unui furnizor care va folosi exclusiv interfata "Modul Furnizor" din Web POSF, OR(conectat prin API) nu va putea accesa mesajele publicate de acesta. Adica, OR trebuie sa foloseasca aceeasi accesare ca si furnizorul pentru a citi mesajele publicate de acesta.

**Comment by bogdannedelcu** [comment]
Daca acelasi Furnizor are o integrare prin API si publica mesaje in POSF prin interfata WebPOSF nu va putea citi acele mesaje in sistemul propriu. POSF nu pune inca la dispozitie mecanism de a citi propriile mesaje trimise.
