### ISSUE TITLE
Fluxuri in eroare

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#90]
Daca dupa GoLive vor exista erori de comunicare intre POSF si sistemele noastre, POSF va retransmite mesajele ramase in eroare care nu au ajuns inca in sistemul OR? POSF va avea confirmarea transmiterii mesajelor?

**Comment by bogdannedelcu** [comment]
La ce fel de erori va referiti?

**Comment by EDistributie** [comment]
Orice tip de eroare care poate bloca transmiterea/primirea unui mesaj.

**Comment by bogdannedelcu** [comment]
POSF pune toate mesajele intr-o coata. Api-ul pus la dispozitie /broker/poolMessage are o optiune prin care se poate relua citirea tuturur mesajelor de la inceput folosind un ID nou de consumator (ex: https://github.com/posfgit/standard/blob/main/TestEnvironment.md#citirea-de-mesaje-folosind-poolmessage)

Asadar nu se pierd mesajele, ele pot fi recitite din POSF.
