### ISSUE TITLE
Flurxuri netransmise in POSF prin API

### ISSUE THREAD

**Issue by EDistributie** [posfgit/standard#93]
Buna ziua,

In cazul in care nu vom reusi sa finalizam dezvoltarea tuturor mesajelor (atat IN cat si OUT) in sistemele proprii pana in 28.08, caz foarte probabil, care este modalitatea prin care vom transmite aceste mesaje manual astfel incat sa nu existe o dezaliniere intre sistemele tuturor partilor implicate. (de exemplu: ca OR nu vom finaliza pana in data de 28.08 mesajul PlaceDisconectedByOperator si nu vom putea raspunde prin API catre POSF. Putem incarca datele de transmis prin acest flux manual, in interfata Operator, prin fisiere csv sau ce alte metode propuneti?)

Multumesc!

**Comment by bogdannedelcu** [comment]
Puteti incarca manual folosind programul Java de aici https://github.com/posfgit/standard/tree/main/samples/small-company . Se copiaza intr-un folder IN toate mesajele care se doresc a fi transmise, se porneste programul folosind user/pass de API iar acesta va transmite toate mesajele spre POSF. Raspunsul va fi salvat in folderul OUT.
