### ISSUE TITLE
Mediu de staging / info ANRE ref sedinta tehnica din 04.08.2022

### ISSUE THREAD

**Issue by GabrielaFlorescu** [posfgit/standard#98]
Ref "De asemenea, reiterăm mesajul din GIT și din grupul de whatsapp că începând din 27.07.2022 este disponibil mediul de staging la adresa [http://posf-staging.anre.ro]. Vă rugam să încărcați toate datele pe mediul de staging astfel încât cel târziu până în data de 08.08.2022 să putem identifica și remedia eventuale probleme în funcționare, de performanța sau posibile disfuncționalități."

Va rugam sa ne precizati:
- unde anume in GIT este acest mesaj la care se face referire?
- despre ce grup de whatsapp este vorba? de ce nu sunt toti participantii la piata acolo?
- cand a fost comunicat acest deadline de 8 AUG si care sunt asteptarile in privinta acestuia, avand in vedere ca noi am aflat de el astazi, practic cu 3 zile inainte?

**Comment by bogdannedelcu** [comment]
https://chat.whatsapp.com/IfwRJkWz8sC3GUBSmbHtB3

accesati pentru join
